using System.ComponentModel;

/*
 * https://cdn.bootcss.com/jquery/1.12.4/jquery.js
  function load(js){
    var s = document.createElement('script');  
    s.setAttribute('type','text/javascript');  
    s.setAttribute('src',js);  
    var head = document.getElementsByTagName('head');  
    head[0].appendChild(s);  

    }
load("https://cdn.bootcss.com/jquery/1.12.4/jquery.js");
  
var obj=$("div.row div");
var out="";
obj.each(function() {     
    var tem=$(this);      
    var v1=tem.find("span.text-muted").text();
    var v2=tem.find("i").text();
    var ke2=tem.text().replace(v2,"").replace(v1,"");
    var ke=ke2.replace(/[\r\n]/g,"").replace(/[ ]/g,"").replace(/-/g,"_").replace("(alias)","").replace(/4.0/g,"").replace(/4.1/g,"").replace(/4.2/g,"").replace(/4.3/g,"").replace(/4.4/g,"").replace(/4.5/g,"").replace(/4.6/g,"").replace(/4.7/g,"");
    var vv=v1.replace("[","").replace("]","").replace(";","").replace("(alias)","");
    var top="[Description(\""+vv+"\")]\r\n";
    out+=top+ke+",\r\n";
});
console.log(out);
 */
/*使用正则 \[\\u.*\]*/

namespace ay.contentcore.Mgr
{
    /// <summary>
    /// fontawesome字体C#
    /// 作者:杨洋
    /// 版本fontawesome 4.7
    /// 收集. fontawesome 2016-12-9 17:43:47
    /// </summary>
    public enum AyFontAweSomeEnum
    {
        [Description("\uf26e")]
        fa_500px,
        [Description("\uf2b9")]
        fa_address_book,
        [Description("\uf2ba")]
        fa_address_book_o,
        [Description("\uf2bb")]
        fa_address_card,
        [Description("\uf2bc")]
        fa_address_card_o,
        [Description("\uf042")]
        fa_adjust,
        [Description("\uf170")]
        fa_adn,
        [Description("\uf037")]
        fa_align_center,
        [Description("\uf039")]
        fa_align_justify,
        [Description("\uf036")]
        fa_align_left,
        [Description("\uf038")]
        fa_align_right,
        [Description("\uf270")]
        fa_amazon,
        [Description("\uf0f9")]
        fa_ambulance,
        [Description("\uf2a3")]
        fa_american_sign_language_interpreting,
        [Description("\uf13d")]
        fa_anchor,
        [Description("\uf17b")]
        fa_android,
        [Description("\uf209")]
        fa_angellist,
        [Description("\uf103")]
        fa_angle_double_down,
        [Description("\uf100")]
        fa_angle_double_left,
        [Description("\uf101")]
        fa_angle_double_right,
        [Description("\uf102")]
        fa_angle_double_up,
        [Description("\uf107")]
        fa_angle_down,
        [Description("\uf104")]
        fa_angle_left,
        [Description("\uf105")]
        fa_angle_right,
        [Description("\uf106")]
        fa_angle_up,
        [Description("\uf179")]
        fa_apple,
        [Description("\uf187")]
        fa_archive,
        [Description("\uf1fe")]
        fa_area_chart,
        [Description("\uf0ab")]
        fa_arrow_circle_down,
        [Description("\uf0a8")]
        fa_arrow_circle_left,
        [Description("\uf01a")]
        fa_arrow_circle_o_down,
        [Description("\uf190")]
        fa_arrow_circle_o_left,
        [Description("\uf18e")]
        fa_arrow_circle_o_right,
        [Description("\uf01b")]
        fa_arrow_circle_o_up,
        [Description("\uf0a9")]
        fa_arrow_circle_right,
        [Description("\uf0aa")]
        fa_arrow_circle_up,
        [Description("\uf063")]
        fa_arrow_down,
        [Description("\uf060")]
        fa_arrow_left,
        [Description("\uf061")]
        fa_arrow_right,
        [Description("\uf062")]
        fa_arrow_up,
        [Description("\uf047")]
        fa_arrows,
        [Description("\uf0b2")]
        fa_arrows_alt,
        [Description("\uf07e")]
        fa_arrows_h,
        [Description("\uf07d")]
        fa_arrows_v,
        [Description("\uf2a3")]
        fa_asl_interpreting,
        [Description("\uf2a2")]
        fa_assistive_listening_systems,
        [Description("\uf069")]
        fa_asterisk,
        [Description("\uf1fa")]
        fa_at,
        [Description("\uf29e")]
        fa_audio_description,
        [Description("\uf1b9")]
        fa_automobile,
        [Description("\uf04a")]
        fa_backward,
        [Description("\uf24e")]
        fa_balance_scale,
        [Description("\uf05e")]
        fa_ban,
        [Description("\uf2d5")]
        fa_bandcamp,
        [Description("\uf19c")]
        fa_bank,
        [Description("\uf080")]
        fa_bar_chart,
        [Description("\uf080")]
        fa_bar_chart_o,
        [Description("\uf02a")]
        fa_barcode,
        [Description("\uf0c9")]
        fa_bars,
        [Description("\uf2cd")]
        fa_bath,
        [Description("\uf2cd")]
        fa_bathtub,
        [Description("\uf240")]
        fa_battery,
        [Description("\uf244")]
        fa_battery_0,
        [Description("\uf243")]
        fa_battery_1,
        [Description("\uf242")]
        fa_battery_2,
        [Description("\uf241")]
        fa_battery_3,
        [Description("\uf240")]
        fa_battery_4,
        [Description("\uf244")]
        fa_battery_empty,
        [Description("\uf240")]
        fa_battery_full,
        [Description("\uf242")]
        fa_battery_half,
        [Description("\uf243")]
        fa_battery_quarter,
        [Description("\uf241")]
        fa_battery_three_quarters,
        [Description("\uf236")]
        fa_bed,
        [Description("\uf0fc")]
        fa_beer,
        [Description("\uf1b4")]
        fa_behance,
        [Description("\uf1b5")]
        fa_behance_square,
        [Description("\uf0f3")]
        fa_bell,
        [Description("\uf0a2")]
        fa_bell_o,
        [Description("\uf1f6")]
        fa_bell_slash,
        [Description("\uf1f7")]
        fa_bell_slash_o,
        [Description("\uf206")]
        fa_bicycle,
        [Description("\uf1e5")]
        fa_binoculars,
        [Description("\uf1fd")]
        fa_birthday_cake,
        [Description("\uf171")]
        fa_bitbucket,
        [Description("\uf172")]
        fa_bitbucket_square,
        [Description("\uf15a")]
        fa_bitcoin,
        [Description("\uf27e")]
        fa_black_tie,
        [Description("\uf29d")]
        fa_blind,
        [Description("\uf293")]
        fa_bluetooth,
        [Description("\uf294")]
        fa_bluetooth_b,
        [Description("\uf032")]
        fa_bold,
        [Description("\uf0e7")]
        fa_bolt,
        [Description("\uf1e2")]
        fa_bomb,
        [Description("\uf02d")]
        fa_book,
        [Description("\uf02e")]
        fa_bookmark,
        [Description("\uf097")]
        fa_bookmark_o,
        [Description("\uf2a1")]
        fa_braille,
        [Description("\uf0b1")]
        fa_briefcase,
        [Description("\uf15a")]
        fa_btc,
        [Description("\uf188")]
        fa_bug,
        [Description("\uf1ad")]
        fa_building,
        [Description("\uf0f7")]
        fa_building_o,
        [Description("\uf0a1")]
        fa_bullhorn,
        [Description("\uf140")]
        fa_bullseye,
        [Description("\uf207")]
        fa_bus,
        [Description("\uf20d")]
        fa_buysellads,
        [Description("\uf1ba")]
        fa_cab,
        [Description("\uf1ec")]
        fa_calculator,
        [Description("\uf073")]
        fa_calendar,
        [Description("\uf274")]
        fa_calendar_check_o,
        [Description("\uf272")]
        fa_calendar_minus_o,
        [Description("\uf133")]
        fa_calendar_o,
        [Description("\uf271")]
        fa_calendar_plus_o,
        [Description("\uf273")]
        fa_calendar_times_o,
        [Description("\uf030")]
        fa_camera,
        [Description("\uf083")]
        fa_camera_retro,
        [Description("\uf1b9")]
        fa_car,
        [Description("\uf0d7")]
        fa_caret_down,
        [Description("\uf0d9")]
        fa_caret_left,
        [Description("\uf0da")]
        fa_caret_right,
        [Description("\uf150")]
        fa_caret_square_o_down,
        [Description("\uf191")]
        fa_caret_square_o_left,
        [Description("\uf152")]
        fa_caret_square_o_right,
        [Description("\uf151")]
        fa_caret_square_o_up,
        [Description("\uf0d8")]
        fa_caret_up,
        [Description("\uf218")]
        fa_cart_arrow_down,
        [Description("\uf217")]
        fa_cart_plus,
        [Description("\uf20a")]
        fa_cc,
        [Description("\uf1f3")]
        fa_cc_amex,
        [Description("\uf24c")]
        fa_cc_diners_club,
        [Description("\uf1f2")]
        fa_cc_discover,
        [Description("\uf24b")]
        fa_cc_jcb,
        [Description("\uf1f1")]
        fa_cc_mastercard,
        [Description("\uf1f4")]
        fa_cc_paypal,
        [Description("\uf1f5")]
        fa_cc_stripe,
        [Description("\uf1f0")]
        fa_cc_visa,
        [Description("\uf0a3")]
        fa_certificate,
        [Description("\uf0c1")]
        fa_chain,
        [Description("\uf127")]
        fa_chain_broken,
        [Description("\uf00c")]
        fa_check,
        [Description("\uf058")]
        fa_check_circle,
        [Description("\uf05d")]
        fa_check_circle_o,
        [Description("\uf14a")]
        fa_check_square,
        [Description("\uf046")]
        fa_check_square_o,
        [Description("\uf13a")]
        fa_chevron_circle_down,
        [Description("\uf137")]
        fa_chevron_circle_left,
        [Description("\uf138")]
        fa_chevron_circle_right,
        [Description("\uf139")]
        fa_chevron_circle_up,
        [Description("\uf078")]
        fa_chevron_down,
        [Description("\uf053")]
        fa_chevron_left,
        [Description("\uf054")]
        fa_chevron_right,
        [Description("\uf077")]
        fa_chevron_up,
        [Description("\uf1ae")]
        fa_child,
        [Description("\uf268")]
        fa_chrome,
        [Description("\uf111")]
        fa_circle,
        [Description("\uf10c")]
        fa_circle_o,
        [Description("\uf1ce")]
        fa_circle_o_notch,
        [Description("\uf1db")]
        fa_circle_thin,
        [Description("\uf0ea")]
        fa_clipboard,
        [Description("\uf017")]
        fa_clock_o,
        [Description("\uf24d")]
        fa_clone,
        [Description("\uf00d")]
        fa_close,
        [Description("\uf0c2")]
        fa_cloud,
        [Description("\uf0ed")]
        fa_cloud_download,
        [Description("\uf0ee")]
        fa_cloud_upload,
        [Description("\uf157")]
        fa_cny,
        [Description("\uf121")]
        fa_code,
        [Description("\uf126")]
        fa_code_fork,
        [Description("\uf1cb")]
        fa_codepen,
        [Description("\uf284")]
        fa_codiepie,
        [Description("\uf0f4")]
        fa_coffee,
        [Description("\uf013")]
        fa_cog,
        [Description("\uf085")]
        fa_cogs,
        [Description("\uf0db")]
        fa_columns,
        [Description("\uf075")]
        fa_comment,
        [Description("\uf0e5")]
        fa_comment_o,
        [Description("\uf27a")]
        fa_commenting,
        [Description("\uf27b")]
        fa_commenting_o,
        [Description("\uf086")]
        fa_comments,
        [Description("\uf0e6")]
        fa_comments_o,
        [Description("\uf14e")]
        fa_compass,
        [Description("\uf066")]
        fa_compress,
        [Description("\uf20e")]
        fa_connectdevelop,
        [Description("\uf26d")]
        fa_contao,
        [Description("\uf0c5")]
        fa_copy,
        [Description("\uf1f9")]
        fa_copyright,
        [Description("\uf25e")]
        fa_creative_commons,
        [Description("\uf09d")]
        fa_credit_card,
        [Description("\uf283")]
        fa_credit_card_alt,
        [Description("\uf125")]
        fa_crop,
        [Description("\uf05b")]
        fa_crosshairs,
        [Description("\uf13c")]
        fa_css3,
        [Description("\uf1b2")]
        fa_cube,
        [Description("\uf1b3")]
        fa_cubes,
        [Description("\uf0c4")]
        fa_cut,
        [Description("\uf0f5")]
        fa_cutlery,
        [Description("\uf0e4")]
        fa_dashboard,
        [Description("\uf210")]
        fa_dashcube,
        [Description("\uf1c0")]
        fa_database,
        [Description("\uf2a4")]
        fa_deaf,
        [Description("\uf2a4")]
        fa_deafness,
        [Description("\uf03b")]
        fa_dedent,
        [Description("\uf1a5")]
        fa_delicious,
        [Description("\uf108")]
        fa_desktop,
        [Description("\uf1bd")]
        fa_deviantart,
        [Description("\uf219")]
        fa_diamond,
        [Description("\uf1a6")]
        fa_digg,
        [Description("\uf155")]
        fa_dollar,
        [Description("\uf192")]
        fa_dot_circle_o,
        [Description("\uf019")]
        fa_download,
        [Description("\uf17d")]
        fa_dribbble,
        [Description("\uf2c2")]
        fa_drivers_license,
        [Description("\uf2c3")]
        fa_drivers_license_o,
        [Description("\uf16b")]
        fa_dropbox,
        [Description("\uf1a9")]
        fa_drupal,
        [Description("\uf282")]
        fa_edge,
        [Description("\uf044")]
        fa_edit,
        [Description("\uf2da")]
        fa_eercast,
        [Description("\uf052")]
        fa_eject,
        [Description("\uf141")]
        fa_ellipsis_h,
        [Description("\uf142")]
        fa_ellipsis_v,
        [Description("\uf1d1")]
        fa_empire,
        [Description("\uf0e0")]
        fa_envelope,
        [Description("\uf003")]
        fa_envelope_o,
        [Description("\uf2b6")]
        fa_envelope_open,
        [Description("\uf2b7")]
        fa_envelope_open_o,
        [Description("\uf199")]
        fa_envelope_square,
        [Description("\uf299")]
        fa_envira,
        [Description("\uf12d")]
        fa_eraser,
        [Description("\uf2d7")]
        fa_etsy,
        [Description("\uf153")]
        fa_eur,
        [Description("\uf153")]
        fa_euro,
        [Description("\uf0ec")]
        fa_exchange,
        [Description("\uf12a")]
        fa_exclamation,
        [Description("\uf06a")]
        fa_exclamation_circle,
        [Description("\uf071")]
        fa_exclamation_triangle,
        [Description("\uf065")]
        fa_expand,
        [Description("\uf23e")]
        fa_expeditedssl,
        [Description("\uf08e")]
        fa_external_link,
        [Description("\uf14c")]
        fa_external_link_square,
        [Description("\uf06e")]
        fa_eye,
        [Description("\uf070")]
        fa_eye_slash,
        [Description("\uf1fb")]
        fa_eyedropper,
        [Description("\uf2b4")]
        fa_fa,
        [Description("\uf09a")]
        fa_facebook,
        [Description("\uf09a")]
        fa_facebook_f,
        [Description("\uf230")]
        fa_facebook_official,
        [Description("\uf082")]
        fa_facebook_square,
        [Description("\uf049")]
        fa_fast_backward,
        [Description("\uf050")]
        fa_fast_forward,
        [Description("\uf1ac")]
        fa_fax,
        [Description("\uf09e")]
        fa_feed,
        [Description("\uf182")]
        fa_female,
        [Description("\uf0fb")]
        fa_fighter_jet,
        [Description("\uf15b")]
        fa_file,
        [Description("\uf1c6")]
        fa_file_archive_o,
        [Description("\uf1c7")]
        fa_file_audio_o,
        [Description("\uf1c9")]
        fa_file_code_o,
        [Description("\uf1c3")]
        fa_file_excel_o,
        [Description("\uf1c5")]
        fa_file_image_o,
        [Description("\uf1c8")]
        fa_file_movie_o,
        [Description("\uf016")]
        fa_file_o,
        [Description("\uf1c1")]
        fa_file_pdf_o,
        [Description("\uf1c5")]
        fa_file_photo_o,
        [Description("\uf1c5")]
        fa_file_picture_o,
        [Description("\uf1c4")]
        fa_file_powerpoint_o,
        [Description("\uf1c7")]
        fa_file_sound_o,
        [Description("\uf15c")]
        fa_file_text,
        [Description("\uf0f6")]
        fa_file_text_o,
        [Description("\uf1c8")]
        fa_file_video_o,
        [Description("\uf1c2")]
        fa_file_word_o,
        [Description("\uf1c6")]
        fa_file_zip_o,
        [Description("\uf0c5")]
        fa_files_o,
        [Description("\uf008")]
        fa_film,
        [Description("\uf0b0")]
        fa_filter,
        [Description("\uf06d")]
        fa_fire,
        [Description("\uf134")]
        fa_fire_extinguisher,
        [Description("\uf269")]
        fa_firefox,
        [Description("\uf2b0")]
        fa_first_order,
        [Description("\uf024")]
        fa_flag,
        [Description("\uf11e")]
        fa_flag_checkered,
        [Description("\uf11d")]
        fa_flag_o,
        [Description("\uf0e7")]
        fa_flash,
        [Description("\uf0c3")]
        fa_flask,
        [Description("\uf16e")]
        fa_flickr,
        [Description("\uf0c7")]
        fa_floppy_o,
        [Description("\uf07b")]
        fa_folder,
        [Description("\uf114")]
        fa_folder_o,
        [Description("\uf07c")]
        fa_folder_open,
        [Description("\uf115")]
        fa_folder_open_o,
        [Description("\uf031")]
        fa_font,
        [Description("\uf2b4")]
        fa_font_awesome,
        [Description("\uf280")]
        fa_fonticons,
        [Description("\uf286")]
        fa_fort_awesome,
        [Description("\uf211")]
        fa_forumbee,
        [Description("\uf04e")]
        fa_forward,
        [Description("\uf180")]
        fa_foursquare,
        [Description("\uf2c5")]
        fa_free_code_camp,
        [Description("\uf119")]
        fa_frown_o,
        [Description("\uf1e3")]
        fa_futbol_o,
        [Description("\uf11b")]
        fa_gamepad,
        [Description("\uf0e3")]
        fa_gavel,
        [Description("\uf154")]
        fa_gbp,
        [Description("\uf1d1")]
        fa_ge,
        [Description("\uf013")]
        fa_gear,
        [Description("\uf085")]
        fa_gears,
        [Description("\uf22d")]
        fa_genderless,
        [Description("\uf265")]
        fa_get_pocket,
        [Description("\uf260")]
        fa_gg,
        [Description("\uf261")]
        fa_gg_circle,
        [Description("\uf06b")]
        fa_gift,
        [Description("\uf1d3")]
        fa_git,
        [Description("\uf1d2")]
        fa_git_square,
        [Description("\uf09b")]
        fa_github,
        [Description("\uf113")]
        fa_github_alt,
        [Description("\uf092")]
        fa_github_square,
        [Description("\uf296")]
        fa_gitlab,
        [Description("\uf184")]
        fa_gittip,
        [Description("\uf000")]
        fa_glass,
        [Description("\uf2a5")]
        fa_glide,
        [Description("\uf2a6")]
        fa_glide_g,
        [Description("\uf0ac")]
        fa_globe,
        [Description("\uf1a0")]
        fa_google,
        [Description("\uf0d5")]
        fa_google_plus,
        [Description("\uf2b3")]
        fa_google_plus_circle,
        [Description("\uf2b3")]
        fa_google_plus_official,
        [Description("\uf0d4")]
        fa_google_plus_square,
        [Description("\uf1ee")]
        fa_google_wallet,
        [Description("\uf19d")]
        fa_graduation_cap,
        [Description("\uf184")]
        fa_gratipay,
        [Description("\uf2d6")]
        fa_grav,
        [Description("\uf0c0")]
        fa_group,
        [Description("\uf0fd")]
        fa_h_square,
        [Description("\uf1d4")]
        fa_hacker_news,
        [Description("\uf255")]
        fa_hand_grab_o,
        [Description("\uf258")]
        fa_hand_lizard_o,
        [Description("\uf0a7")]
        fa_hand_o_down,
        [Description("\uf0a5")]
        fa_hand_o_left,
        [Description("\uf0a4")]
        fa_hand_o_right,
        [Description("\uf0a6")]
        fa_hand_o_up,
        [Description("\uf256")]
        fa_hand_paper_o,
        [Description("\uf25b")]
        fa_hand_peace_o,
        [Description("\uf25a")]
        fa_hand_pointer_o,
        [Description("\uf255")]
        fa_hand_rock_o,
        [Description("\uf257")]
        fa_hand_scissors_o,
        [Description("\uf259")]
        fa_hand_spock_o,
        [Description("\uf256")]
        fa_hand_stop_o,
        [Description("\uf2b5")]
        fa_handshake_o,
        [Description("\uf2a4")]
        fa_hard_of_hearing,
        [Description("\uf292")]
        fa_hashtag,
        [Description("\uf0a0")]
        fa_hdd_o,
        [Description("\uf1dc")]
        fa_header,
        [Description("\uf025")]
        fa_headphones,
        [Description("\uf004")]
        fa_heart,
        [Description("\uf08a")]
        fa_heart_o,
        [Description("\uf21e")]
        fa_heartbeat,
        [Description("\uf1da")]
        fa_history,
        [Description("\uf015")]
        fa_home,
        [Description("\uf0f8")]
        fa_hospital_o,
        [Description("\uf236")]
        fa_hotel,
        [Description("\uf254")]
        fa_hourglass,
        [Description("\uf251")]
        fa_hourglass_1,
        [Description("\uf252")]
        fa_hourglass_2,
        [Description("\uf253")]
        fa_hourglass_3,
        [Description("\uf253")]
        fa_hourglass_end,
        [Description("\uf252")]
        fa_hourglass_half,
        [Description("\uf250")]
        fa_hourglass_o,
        [Description("\uf251")]
        fa_hourglass_start,
        [Description("\uf27c")]
        fa_houzz,
        [Description("\uf13b")]
        fa_html5,
        [Description("\uf246")]
        fa_i_cursor,
        [Description("\uf2c1")]
        fa_id_badge,
        [Description("\uf2c2")]
        fa_id_card,
        [Description("\uf2c3")]
        fa_id_card_o,
        [Description("\uf20b")]
        fa_ils,
        [Description("\uf03e")]
        fa_image,
        [Description("\uf2d8")]
        fa_imdb,
        [Description("\uf01c")]
        fa_inbox,
        [Description("\uf03c")]
        fa_indent,
        [Description("\uf275")]
        fa_industry,
        [Description("\uf129")]
        fa_info,
        [Description("\uf05a")]
        fa_info_circle,
        [Description("\uf156")]
        fa_inr,
        [Description("\uf16d")]
        fa_instagram,
        [Description("\uf19c")]
        fa_institution,
        [Description("\uf26b")]
        fa_internet_explorer,
        [Description("\uf224")]
        fa_intersex,
        [Description("\uf208")]
        fa_ioxhost,
        [Description("\uf033")]
        fa_italic,
        [Description("\uf1aa")]
        fa_joomla,
        [Description("\uf157")]
        fa_jpy,
        [Description("\uf1cc")]
        fa_jsfiddle,
        [Description("\uf084")]
        fa_key,
        [Description("\uf11c")]
        fa_keyboard_o,
        [Description("\uf159")]
        fa_krw,
        [Description("\uf1ab")]
        fa_language,
        [Description("\uf109")]
        fa_laptop,
        [Description("\uf202")]
        fa_lastfm,
        [Description("\uf203")]
        fa_lastfm_square,
        [Description("\uf06c")]
        fa_leaf,
        [Description("\uf212")]
        fa_leanpub,
        [Description("\uf0e3")]
        fa_legal,
        [Description("\uf094")]
        fa_lemon_o,
        [Description("\uf149")]
        fa_level_down,
        [Description("\uf148")]
        fa_level_up,
        [Description("\uf1cd")]
        fa_life_bouy,
        [Description("\uf1cd")]
        fa_life_buoy,
        [Description("\uf1cd")]
        fa_life_ring,
        [Description("\uf1cd")]
        fa_life_saver,
        [Description("\uf0eb")]
        fa_lightbulb_o,
        [Description("\uf201")]
        fa_line_chart,
        [Description("\uf0c1")]
        fa_link,
        [Description("\uf0e1")]
        fa_linkedin,
        [Description("\uf08c")]
        fa_linkedin_square,
        [Description("\uf2b8")]
        fa_linode,
        [Description("\uf17c")]
        fa_linux,
        [Description("\uf03a")]
        fa_list,
        [Description("\uf022")]
        fa_list_alt,
        [Description("\uf0cb")]
        fa_list_ol,
        [Description("\uf0ca")]
        fa_list_ul,
        [Description("\uf124")]
        fa_location_arrow,
        [Description("\uf023")]
        fa_lock,
        [Description("\uf175")]
        fa_long_arrow_down,
        [Description("\uf177")]
        fa_long_arrow_left,
        [Description("\uf178")]
        fa_long_arrow_right,
        [Description("\uf176")]
        fa_long_arrow_up,
        [Description("\uf2a8")]
        fa_low_vision,
        [Description("\uf0d0")]
        fa_magic,
        [Description("\uf076")]
        fa_magnet,
        [Description("\uf064")]
        fa_mail_forward,
        [Description("\uf112")]
        fa_mail_reply,
        [Description("\uf122")]
        fa_mail_reply_all,
        [Description("\uf183")]
        fa_male,
        [Description("\uf279")]
        fa_map,
        [Description("\uf041")]
        fa_map_marker,
        [Description("\uf278")]
        fa_map_o,
        [Description("\uf276")]
        fa_map_pin,
        [Description("\uf277")]
        fa_map_signs,
        [Description("\uf222")]
        fa_mars,
        [Description("\uf227")]
        fa_mars_double,
        [Description("\uf229")]
        fa_mars_stroke,
        [Description("\uf22b")]
        fa_mars_stroke_h,
        [Description("\uf22a")]
        fa_mars_stroke_v,
        [Description("\uf136")]
        fa_maxcdn,
        [Description("\uf20c")]
        fa_meanpath,
        [Description("\uf23a")]
        fa_medium,
        [Description("\uf0fa")]
        fa_medkit,
        [Description("\uf2e0")]
        fa_meetup,
        [Description("\uf11a")]
        fa_meh_o,
        [Description("\uf223")]
        fa_mercury,
        [Description("\uf2db")]
        fa_microchip,
        [Description("\uf130")]
        fa_microphone,
        [Description("\uf131")]
        fa_microphone_slash,
        [Description("\uf068")]
        fa_minus,
        [Description("\uf056")]
        fa_minus_circle,
        [Description("\uf146")]
        fa_minus_square,
        [Description("\uf147")]
        fa_minus_square_o,
        [Description("\uf289")]
        fa_mixcloud,
        [Description("\uf10b")]
        fa_mobile,
        [Description("\uf10b")]
        fa_mobile_phone,
        [Description("\uf285")]
        fa_modx,
        [Description("\uf0d6")]
        fa_money,
        [Description("\uf186")]
        fa_moon_o,
        [Description("\uf19d")]
        fa_mortar_board,
        [Description("\uf21c")]
        fa_motorcycle,
        [Description("\uf245")]
        fa_mouse_pointer,
        [Description("\uf001")]
        fa_music,
        [Description("\uf0c9")]
        fa_navicon,
        [Description("\uf22c")]
        fa_neuter,
        [Description("\uf1ea")]
        fa_newspaper_o,
        [Description("\uf247")]
        fa_object_group,
        [Description("\uf248")]
        fa_object_ungroup,
        [Description("\uf263")]
        fa_odnoklassniki,
        [Description("\uf264")]
        fa_odnoklassniki_square,
        [Description("\uf23d")]
        fa_opencart,
        [Description("\uf19b")]
        fa_openid,
        [Description("\uf26a")]
        fa_opera,
        [Description("\uf23c")]
        fa_optin_monster,
        [Description("\uf03b")]
        fa_outdent,
        [Description("\uf18c")]
        fa_pagelines,
        [Description("\uf1fc")]
        fa_paint_brush,
        [Description("\uf1d8")]
        fa_paper_plane,
        [Description("\uf1d9")]
        fa_paper_plane_o,
        [Description("\uf0c6")]
        fa_paperclip,
        [Description("\uf1dd")]
        fa_paragraph,
        [Description("\uf0ea")]
        fa_paste,
        [Description("\uf04c")]
        fa_pause,
        [Description("\uf28b")]
        fa_pause_circle,
        [Description("\uf28c")]
        fa_pause_circle_o,
        [Description("\uf1b0")]
        fa_paw,
        [Description("\uf1ed")]
        fa_paypal,
        [Description("\uf040")]
        fa_pencil,
        [Description("\uf14b")]
        fa_pencil_square,
        [Description("\uf044")]
        fa_pencil_square_o,
        [Description("\uf295")]
        fa_percent,
        [Description("\uf095")]
        fa_phone,
        [Description("\uf098")]
        fa_phone_square,
        [Description("\uf03e")]
        fa_photo,
        [Description("\uf03e")]
        fa_picture_o,
        [Description("\uf200")]
        fa_pie_chart,
        [Description("\uf2ae")]
        fa_pied_piper,
        [Description("\uf1a8")]
        fa_pied_piper_alt,
        [Description("\uf1a7")]
        fa_pied_piper_pp,
        [Description("\uf0d2")]
        fa_pinterest,
        [Description("\uf231")]
        fa_pinterest_p,
        [Description("\uf0d3")]
        fa_pinterest_square,
        [Description("\uf072")]
        fa_plane,
        [Description("\uf04b")]
        fa_play,
        [Description("\uf144")]
        fa_play_circle,
        [Description("\uf01d")]
        fa_play_circle_o,
        [Description("\uf1e6")]
        fa_plug,
        [Description("\uf067")]
        fa_plus,
        [Description("\uf055")]
        fa_plus_circle,
        [Description("\uf0fe")]
        fa_plus_square,
        [Description("\uf196")]
        fa_plus_square_o,
        [Description("\uf2ce")]
        fa_podcast,
        [Description("\uf011")]
        fa_power_off,
        [Description("\uf02f")]
        fa_print,
        [Description("\uf288")]
        fa_product_hunt,
        [Description("\uf12e")]
        fa_puzzle_piece,
        [Description("\uf1d6")]
        fa_qq,
        [Description("\uf029")]
        fa_qrcode,
        [Description("\uf128")]
        fa_question,
        [Description("\uf059")]
        fa_question_circle,
        [Description("\uf29c")]
        fa_question_circle_o,
        [Description("\uf2c4")]
        fa_quora,
        [Description("\uf10d")]
        fa_quote_left,
        [Description("\uf10e")]
        fa_quote_right,
        [Description("\uf1d0")]
        fa_ra,
        [Description("\uf074")]
        fa_random,
        [Description("\uf2d9")]
        fa_ravelry,
        [Description("\uf1d0")]
        fa_rebel,
        [Description("\uf1b8")]
        fa_recycle,
        [Description("\uf1a1")]
        fa_reddit,
        [Description("\uf281")]
        fa_reddit_alien,
        [Description("\uf1a2")]
        fa_reddit_square,
        [Description("\uf021")]
        fa_refresh,
        [Description("\uf25d")]
        fa_registered,
        [Description("\uf00d")]
        fa_remove,
        [Description("\uf18b")]
        fa_renren,
        [Description("\uf0c9")]
        fa_reorder,
        [Description("\uf01e")]
        fa_repeat,
        [Description("\uf112")]
        fa_reply,
        [Description("\uf122")]
        fa_reply_all,
        [Description("\uf1d0")]
        fa_resistance,
        [Description("\uf079")]
        fa_retweet,
        [Description("\uf157")]
        fa_rmb,
        [Description("\uf018")]
        fa_road,
        [Description("\uf135")]
        fa_rocket,
        [Description("\uf0e2")]
        fa_rotate_left,
        [Description("\uf01e")]
        fa_rotate_right,
        [Description("\uf158")]
        fa_rouble,
        [Description("\uf09e")]
        fa_rss,
        [Description("\uf143")]
        fa_rss_square,
        [Description("\uf158")]
        fa_rub,
        [Description("\uf158")]
        fa_ruble,
        [Description("\uf156")]
        fa_rupee,
        [Description("\uf2cd")]
        fa_s15,
        [Description("\uf267")]
        fa_safari,
        [Description("\uf0c7")]
        fa_save,
        [Description("\uf0c4")]
        fa_scissors,
        [Description("\uf28a")]
        fa_scribd,
        [Description("\uf002")]
        fa_search,
        [Description("\uf010")]
        fa_search_minus,
        [Description("\uf00e")]
        fa_search_plus,
        [Description("\uf213")]
        fa_sellsy,
        [Description("\uf1d8")]
        fa_send,
        [Description("\uf1d9")]
        fa_send_o,
        [Description("\uf233")]
        fa_server,
        [Description("\uf064")]
        fa_share,
        [Description("\uf1e0")]
        fa_share_alt,
        [Description("\uf1e1")]
        fa_share_alt_square,
        [Description("\uf14d")]
        fa_share_square,
        [Description("\uf045")]
        fa_share_square_o,
        [Description("\uf20b")]
        fa_shekel,
        [Description("\uf20b")]
        fa_sheqel,
        [Description("\uf132")]
        fa_shield,
        [Description("\uf21a")]
        fa_ship,
        [Description("\uf214")]
        fa_shirtsinbulk,
        [Description("\uf290")]
        fa_shopping_bag,
        [Description("\uf291")]
        fa_shopping_basket,
        [Description("\uf07a")]
        fa_shopping_cart,
        [Description("\uf2cc")]
        fa_shower,
        [Description("\uf090")]
        fa_sign_in,
        [Description("\uf2a7")]
        fa_sign_language,
        [Description("\uf08b")]
        fa_sign_out,
        [Description("\uf012")]
        fa_signal,
        [Description("\uf2a7")]
        fa_signing,
        [Description("\uf215")]
        fa_simplybuilt,
        [Description("\uf0e8")]
        fa_sitemap,
        [Description("\uf216")]
        fa_skyatlas,
        [Description("\uf17e")]
        fa_skype,
        [Description("\uf198")]
        fa_slack,
        [Description("\uf1de")]
        fa_sliders,
        [Description("\uf1e7")]
        fa_slideshare,
        [Description("\uf118")]
        fa_smile_o,
        [Description("\uf2ab")]
        fa_snapchat,
        [Description("\uf2ac")]
        fa_snapchat_ghost,
        [Description("\uf2ad")]
        fa_snapchat_square,
        [Description("\uf2dc")]
        fa_snowflake_o,
        [Description("\uf1e3")]
        fa_soccer_ball_o,
        [Description("\uf0dc")]
        fa_sort,
        [Description("\uf15d")]
        fa_sort_alpha_asc,
        [Description("\uf15e")]
        fa_sort_alpha_desc,
        [Description("\uf160")]
        fa_sort_amount_asc,
        [Description("\uf161")]
        fa_sort_amount_desc,
        [Description("\uf0de")]
        fa_sort_asc,
        [Description("\uf0dd")]
        fa_sort_desc,
        [Description("\uf0dd")]
        fa_sort_down,
        [Description("\uf162")]
        fa_sort_numeric_asc,
        [Description("\uf163")]
        fa_sort_numeric_desc,
        [Description("\uf0de")]
        fa_sort_up,
        [Description("\uf1be")]
        fa_soundcloud,
        [Description("\uf197")]
        fa_space_shuttle,
        [Description("\uf110")]
        fa_spinner,
        [Description("\uf1b1")]
        fa_spoon,
        [Description("\uf1bc")]
        fa_spotify,
        [Description("\uf0c8")]
        fa_square,
        [Description("\uf096")]
        fa_square_o,
        [Description("\uf18d")]
        fa_stack_exchange,
        [Description("\uf16c")]
        fa_stack_overflow,
        [Description("\uf005")]
        fa_star,
        [Description("\uf089")]
        fa_star_half,
        [Description("\uf123")]
        fa_star_half_empty,
        [Description("\uf123")]
        fa_star_half_full,
        [Description("\uf123")]
        fa_star_half_o,
        [Description("\uf006")]
        fa_star_o,
        [Description("\uf1b6")]
        fa_steam,
        [Description("\uf1b7")]
        fa_steam_square,
        [Description("\uf048")]
        fa_step_backward,
        [Description("\uf051")]
        fa_step_forward,
        [Description("\uf0f1")]
        fa_stethoscope,
        [Description("\uf249")]
        fa_sticky_note,
        [Description("\uf24a")]
        fa_sticky_note_o,
        [Description("\uf04d")]
        fa_stop,
        [Description("\uf28d")]
        fa_stop_circle,
        [Description("\uf28e")]
        fa_stop_circle_o,
        [Description("\uf21d")]
        fa_street_view,
        [Description("\uf0cc")]
        fa_strikethrough,
        [Description("\uf1a4")]
        fa_stumbleupon,
        [Description("\uf1a3")]
        fa_stumbleupon_circle,
        [Description("\uf12c")]
        fa_subscript,
        [Description("\uf239")]
        fa_subway,
        [Description("\uf0f2")]
        fa_suitcase,
        [Description("\uf185")]
        fa_sun_o,
        [Description("\uf2dd")]
        fa_superpowers,
        [Description("\uf12b")]
        fa_superscript,
        [Description("\uf1cd")]
        fa_support,
        [Description("\uf0ce")]
        fa_table,
        [Description("\uf10a")]
        fa_tablet,
        [Description("\uf0e4")]
        fa_tachometer,
        [Description("\uf02b")]
        fa_tag,
        [Description("\uf02c")]
        fa_tags,
        [Description("\uf0ae")]
        fa_tasks,
        [Description("\uf1ba")]
        fa_taxi,
        [Description("\uf2c6")]
        fa_telegram,
        [Description("\uf26c")]
        fa_television,
        [Description("\uf1d5")]
        fa_tencent_weibo,
        [Description("\uf120")]
        fa_terminal,
        [Description("\uf034")]
        fa_text_height,
        [Description("\uf035")]
        fa_text_width,
        [Description("\uf00a")]
        fa_th,
        [Description("\uf009")]
        fa_th_large,
        [Description("\uf00b")]
        fa_th_list,
        [Description("\uf2b2")]
        fa_themeisle,
        [Description("\uf2c7")]
        fa_thermometer,
        [Description("\uf2cb")]
        fa_thermometer_0,
        [Description("\uf2ca")]
        fa_thermometer_1,
        [Description("\uf2c9")]
        fa_thermometer_2,
        [Description("\uf2c8")]
        fa_thermometer_3,
        [Description("\uf2c7")]
        fa_thermometer_4,
        [Description("\uf2cb")]
        fa_thermometer_empty,
        [Description("\uf2c7")]
        fa_thermometer_full,
        [Description("\uf2c9")]
        fa_thermometer_half,
        [Description("\uf2ca")]
        fa_thermometer_quarter,
        [Description("\uf2c8")]
        fa_thermometer_three_quarters,
        [Description("\uf08d")]
        fa_thumb_tack,
        [Description("\uf165")]
        fa_thumbs_down,
        [Description("\uf088")]
        fa_thumbs_o_down,
        [Description("\uf087")]
        fa_thumbs_o_up,
        [Description("\uf164")]
        fa_thumbs_up,
        [Description("\uf145")]
        fa_ticket,
        [Description("\uf00d")]
        fa_times,
        [Description("\uf057")]
        fa_times_circle,
        [Description("\uf05c")]
        fa_times_circle_o,
        [Description("\uf2d3")]
        fa_times_rectangle,
        [Description("\uf2d4")]
        fa_times_rectangle_o,
        [Description("\uf043")]
        fa_tint,
        [Description("\uf150")]
        fa_toggle_down,
        [Description("\uf191")]
        fa_toggle_left,
        [Description("\uf204")]
        fa_toggle_off,
        [Description("\uf205")]
        fa_toggle_on,
        [Description("\uf152")]
        fa_toggle_right,
        [Description("\uf151")]
        fa_toggle_up,
        [Description("\uf25c")]
        fa_trademark,
        [Description("\uf238")]
        fa_train,
        [Description("\uf224")]
        fa_transgender,
        [Description("\uf225")]
        fa_transgender_alt,
        [Description("\uf1f8")]
        fa_trash,
        [Description("\uf014")]
        fa_trash_o,
        [Description("\uf1bb")]
        fa_tree,
        [Description("\uf181")]
        fa_trello,
        [Description("\uf262")]
        fa_tripadvisor,
        [Description("\uf091")]
        fa_trophy,
        [Description("\uf0d1")]
        fa_truck,
        [Description("\uf195")]
        fa_try,
        [Description("\uf1e4")]
        fa_tty,
        [Description("\uf173")]
        fa_tumblr,
        [Description("\uf174")]
        fa_tumblr_square,
        [Description("\uf195")]
        fa_turkish_lira,
        [Description("\uf26c")]
        fa_tv,
        [Description("\uf1e8")]
        fa_twitch,
        [Description("\uf099")]
        fa_twitter,
        [Description("\uf081")]
        fa_twitter_square,
        [Description("\uf0e9")]
        fa_umbrella,
        [Description("\uf0cd")]
        fa_underline,
        [Description("\uf0e2")]
        fa_undo,
        [Description("\uf29a")]
        fa_universal_access,
        [Description("\uf19c")]
        fa_university,
        [Description("\uf127")]
        fa_unlink,
        [Description("\uf09c")]
        fa_unlock,
        [Description("\uf13e")]
        fa_unlock_alt,
        [Description("\uf0dc")]
        fa_unsorted,
        [Description("\uf093")]
        fa_upload,
        [Description("\uf287")]
        fa_usb,
        [Description("\uf155")]
        fa_usd,
        [Description("\uf007")]
        fa_user,
        [Description("\uf2bd")]
        fa_user_circle,
        [Description("\uf2be")]
        fa_user_circle_o,
        [Description("\uf0f0")]
        fa_user_md,
        [Description("\uf2c0")]
        fa_user_o,
        [Description("\uf234")]
        fa_user_plus,
        [Description("\uf21b")]
        fa_user_secret,
        [Description("\uf235")]
        fa_user_times,
        [Description("\uf0c0")]
        fa_users,
        [Description("\uf2bb")]
        fa_vcard,
        [Description("\uf2bc")]
        fa_vcard_o,
        [Description("\uf221")]
        fa_venus,
        [Description("\uf226")]
        fa_venus_double,
        [Description("\uf228")]
        fa_venus_mars,
        [Description("\uf237")]
        fa_viacoin,
        [Description("\uf2a9")]
        fa_viadeo,
        [Description("\uf2aa")]
        fa_viadeo_square,
        [Description("\uf03d")]
        fa_video_camera,
        [Description("\uf27d")]
        fa_vimeo,
        [Description("\uf194")]
        fa_vimeo_square,
        [Description("\uf1ca")]
        fa_vine,
        [Description("\uf189")]
        fa_vk,
        [Description("\uf2a0")]
        fa_volume_control_phone,
        [Description("\uf027")]
        fa_volume_down,
        [Description("\uf026")]
        fa_volume_off,
        [Description("\uf028")]
        fa_volume_up,
        [Description("\uf071")]
        fa_warning,
        [Description("\uf1d7")]
        fa_wechat,
        [Description("\uf18a")]
        fa_weibo,
        [Description("\uf1d7")]
        fa_weixin,
        [Description("\uf232")]
        fa_whatsapp,
        [Description("\uf193")]
        fa_wheelchair,
        [Description("\uf29b")]
        fa_wheelchair_alt,
        [Description("\uf1eb")]
        fa_wifi,
        [Description("\uf266")]
        fa_wikipedia_w,
        [Description("\uf2d3")]
        fa_window_close,
        [Description("\uf2d4")]
        fa_window_close_o,
        [Description("\uf2d0")]
        fa_window_maximize,
        [Description("\uf2d1")]
        fa_window_minimize,
        [Description("\uf2d2")]
        fa_window_restore,
        [Description("\uf17a")]
        fa_windows,
        [Description("\uf159")]
        fa_won,
        [Description("\uf19a")]
        fa_wordpress,
        [Description("\uf297")]
        fa_wpbeginner,
        [Description("\uf2de")]
        fa_wpexplorer,
        [Description("\uf298")]
        fa_wpforms,
        [Description("\uf0ad")]
        fa_wrench,
        [Description("\uf168")]
        fa_xing,
        [Description("\uf169")]
        fa_xing_square,
        [Description("\uf23b")]
        fa_y_combinator,
        [Description("\uf1d4")]
        fa_y_combinator_square,
        [Description("\uf19e")]
        fa_yahoo,
        [Description("\uf23b")]
        fa_yc,
        [Description("\uf1d4")]
        fa_yc_square,
        [Description("\uf1e9")]
        fa_yelp,
        [Description("\uf157")]
        fa_yen,
        [Description("\uf2b1")]
        fa_yoast,
        [Description("\uf167")]
        fa_youtube,
        [Description("\uf16a")]
        fa_youtube_play,
        [Description("\uf166")]
        fa_youtube_square,




    }
}
